---
version: '3.8'
services:
  esphome-editor:
    image: morcatko/esphome-editor:latest
    container_name: esphome-editor
    network_mode: host
    privileged: true
    cap_add: [ALL]
    volumes:
      - /udobnidom/esphome-editor/data:/data
      # Мапируем папку данных
    env_file:
      - stack.env
    restart: unless-stopped
