---
version: '2.4'
services:
  esphome:
    platform: linux/arm64/v8
    image: ghcr.io/esphome/esphome:latest
    container_name: esphome
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - /udobnidom/esphome/config:/config
      - /udobnidom/esphome/pio_cache:/pioenvs
      - /etc/localtime:/etc/localtime:ro
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - PLATFORMIO_RUN_JOBS=2
      - PLATFORMIO_CACHE_DIR=/pioenvs
    mem_limit: 2g
    memswap_limit: 3g
    cpus: "3.0"
