---
version: "3.8"

services:
  kodexplorer:
    image: kodcloud/kodexplorer:latest
    container_name: kodexplorer
    ports:
      - "8081:80"
      # Порт 8081 хоста → порт 80 контейнера
    volumes:
      - "/udobnidom:/var/www/html"
      - "/udobnidom/kodexplorer/data:/data"
      # Корень ОС
    restart: unless-stopped
    #user: "1000:1000"
    #env:
