---
version: '3.8'
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'     # HTTP-трафик
      - '81:81'     # Веб-интерфейс NPM
      - '443:443'   # HTTPS-трафик
    volumes:
      - /udobnidom/nginx-proxy-manager/data:/data
      - /udobnidom/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - homeiot_internal
networks:
  homeiot_internal:
    external: true
