version: "3.8"

services:
  osyshome:
    image: python:3.11-slim
    container_name: osyshome
    build: .
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Moscow
    ports:
      - "5000:5000"
    volumes:
      - /opt/osyshome/config.yaml:/app/config.yaml
      - /opt/osyshome/plugins:/app/plugins
      - /opt/osyshome/data:/app/data
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    command: >
      bash -c "
      pip install pdoc3 &&
      if [ ! -d /app/plugins/Modules ]; then
        echo '🔧 Устанавливаю плагины osysHome...';
        mkdir -p /app/plugins &&
        git clone https://github.com/Anisan/osysHome-Modules.git /app/plugins/Modules &&
        git clone https://github.com/Anisan/osysHome-Objects.git /app/plugins/Objects &&
        git clone https://github.com/Anisan/osysHome-Users.git /app/plugins/Users &&
        git clone https://github.com/Anisan/osysHome-Scheduler.git /app/plugins/Scheduler &&
        git clone https://github.com/Anisan/osysHome-wsServer.git /app/plugins/wsServer &&
        git clone https://github.com/Anisan/osysHome-Dashboard.git /app/plugins/Dashboard &&
        git clone https://github.com/Anisan/osysHome-Mqtt.git /app/plugins/Mqtt;
      fi;
      echo '📄 Генерация документации...';
      pdoc --docformat google --no-show-source --output-dir /app/data/docs settings_sample.py app plugins;
      echo '🚀 Запуск osysHome...';
      python3 main.py"